apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-classifier
  template:
    metadata:
      labels:
        app: text-classifier
    spec:
      containers:
      - name: text-classifier
        image: classifier.azurecr.io/text_classifier:v2
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: text-classifier-service
spec:
  type: LoadBalancer
  selector:
    app: text-classifier
  ports:
    - port: 80
      targetPort: 8000